package scaffold

import (
	"bytes"
	"fmt"
	"time"

	"gopkg.in/yaml.v3"

	"github.com/joppe2001/stackwright/internal/registry"
	"github.com/joppe2001/stackwright/internal/tui"
)

// stackYAML mirrors the file shape documented in the spec (stack.yaml):
//
//	archbuilder: "1.0"
//	app: my-saas
//	generated: <RFC3339>
//	stack:
//	  frontend: { slug: nextjs-14, version: "14.2" }
//	  ...
//
// We keep the key "stackwright" instead of "archbuilder" since we renamed
// the tool. Existing docs that reference archbuilder will need updating —
// that's noted in the README under "renamed".
type stackYAML struct {
	StackWright string                      `yaml:"stackwright"`
	App         string                      `yaml:"app"`
	Generated   string                      `yaml:"generated"`
	Stack       map[string]stackYAMLEntry   `yaml:"stack"`
}

type stackYAMLEntry struct {
	Slug        string `yaml:"slug"`
	Name        string `yaml:"name,omitempty"`
	Description string `yaml:"description,omitempty"`
}

// renderStackYAML serializes the confirmed stack as stack.yaml content.
// Called by engine.Generate for the "<generated stack.yaml>" source marker.
func renderStackYAML(stack tui.Stack, bundle registry.Bundle) ([]byte, error) {
	out := stackYAML{
		StackWright: "1.0",
		App:         stack.AppName,
		Generated:   time.Now().UTC().Format(time.RFC3339),
		Stack:       map[string]stackYAMLEntry{},
	}
	for _, l := range tui.AllLayers {
		slug := stack.Slug(l)
		if slug == "" {
			continue
		}
		entry := stackYAMLEntry{Slug: slug}
		if e, ok := bundle.BySlug(slug); ok {
			entry.Name = e.Name
			entry.Description = e.Description
		}
		out.Stack[string(l)] = entry
	}
	var buf bytes.Buffer
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(out); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// renderSetupMD produces the human-facing SETUP.md by concatenating each
// selected entry's setup_steps section, topped with a title and an index.
func renderSetupMD(stack tui.Stack, bundle registry.Bundle) ([]byte, error) {
	var buf bytes.Buffer
	name := stack.AppName
	if name == "" {
		name = "your project"
	}
	fmt.Fprintf(&buf, "# %s — setup guide\n\n", name)
	fmt.Fprintf(&buf, "Generated by stackwright on %s.\n\n", time.Now().UTC().Format("2006-01-02"))
	fmt.Fprintln(&buf, "This file walks through the steps to finish setting up each technology in your stack.")
	fmt.Fprintln(&buf)

	// Table of contents.
	fmt.Fprintln(&buf, "## Index")
	fmt.Fprintln(&buf)
	for _, l := range tui.AllLayers {
		slug := stack.Slug(l)
		if slug == "" {
			continue
		}
		if e, ok := bundle.BySlug(slug); ok {
			fmt.Fprintf(&buf, "- [%s](#%s) — _%s_\n", e.Name, anchorize(e.Name), string(e.Category))
		}
	}
	fmt.Fprintln(&buf)

	for _, l := range tui.AllLayers {
		slug := stack.Slug(l)
		if slug == "" {
			continue
		}
		e, ok := bundle.BySlug(slug)
		if !ok {
			continue
		}
		fmt.Fprintf(&buf, "## %s\n\n", e.Name)
		if e.Description != "" {
			fmt.Fprintln(&buf, e.Description)
			fmt.Fprintln(&buf)
		}
		if e.DocsURL != "" {
			fmt.Fprintf(&buf, "**Docs:** %s\n\n", e.DocsURL)
		}
		if e.Account != nil && e.Account.Required {
			fmt.Fprintln(&buf, "### Account")
			if e.Account.Note != "" {
				fmt.Fprintln(&buf, e.Account.Note)
			}
			if e.Account.SignupURL != "" {
				fmt.Fprintf(&buf, "\nSign up: %s\n", e.Account.SignupURL)
			}
			fmt.Fprintln(&buf)
		}
		if len(e.SetupSteps) > 0 {
			fmt.Fprintln(&buf, "### Setup steps")
			for _, s := range e.SetupSteps {
				fmt.Fprintf(&buf, "- %s\n", s)
			}
			fmt.Fprintln(&buf)
		}
		if e.BoilerplateSnippet != "" {
			fmt.Fprintln(&buf, "### Boilerplate")
			fmt.Fprintln(&buf, "```")
			fmt.Fprint(&buf, e.BoilerplateSnippet)
			if len(e.BoilerplateSnippet) > 0 && e.BoilerplateSnippet[len(e.BoilerplateSnippet)-1] != '\n' {
				fmt.Fprintln(&buf)
			}
			fmt.Fprintln(&buf, "```")
			fmt.Fprintln(&buf)
		}
	}

	return buf.Bytes(), nil
}

// anchorize turns "Next.js 14" into "nextjs-14" for markdown anchors.
// Keeps things simple — no collision handling because all names in our
// registry are already distinct.
func anchorize(s string) string {
	var b bytes.Buffer
	prev := byte(0)
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch {
		case c >= 'A' && c <= 'Z':
			b.WriteByte(c + 32)
			prev = c + 32
		case (c >= 'a' && c <= 'z') || (c >= '0' && c <= '9'):
			b.WriteByte(c)
			prev = c
		default:
			if prev != '-' && b.Len() > 0 {
				b.WriteByte('-')
				prev = '-'
			}
		}
	}
	out := b.String()
	// trim trailing dash
	for len(out) > 0 && out[len(out)-1] == '-' {
		out = out[:len(out)-1]
	}
	return out
}
